import React, { useEffect, useState } from 'react';
import Title from '../components/ui/Title';
import commuteArts from '../assets/vector/commute-helper-1.svg';
import missionArts from '../assets/vector/mission.svg';
import visionArts from '../assets/vector/vision.svg';

const aboutNavLinks = [
  {
    id: 'about-us',
    title: 'About',
    description:
      'We are committed to transforming daily commutes into sustainable and efficient journeys. Our platform bridges the gap between riders and passengers, enabling them to share rides, reduce travel expenses, and contribute to a greener planet. By connecting people traveling the same route, we ensure that every empty seat serves a purpose. We empower our users to make a positive impact on the environment, one shared ride at a time. Join us in our mission to create a more sustainable future for all. Together, we can make a difference.',
    image: commuteArts,
  },
  {
    id: 'our-mission',
    title: 'Mission',
    description:
      'Our mission is to reduce the number of empty car seats on the road by connecting drivers with passengers traveling the same route. We aim to create a more sustainable and efficient transportation system that benefits both the environment and the community. By encouraging ride-sharing, we help reduce traffic congestion, lower carbon emissions, and save money on fuel costs. Our platform is designed to make carpooling convenient, safe, and affordable for everyone. We believe that by working together, we can build a better future for all.',
    image: missionArts,
  },
  {
    id: 'our-vision',
    title: 'Vision',
    description:
      'Our vision is to revolutionize the way people commute by making carpooling the preferred mode of transportation. We envision a world where every car seat is filled with passengers who share the same destination. By promoting ride-sharing, we aim to create a more sustainable and inclusive society that benefits everyone. We believe that by leveraging technology and innovation, we can transform the way people travel and reduce their carbon footprint. Our goal is to build a global community of like-minded individuals who are committed to making a positive impact on the environment. Join us in our journey to create a greener and more connected world.',
    image: visionArts,
  },
];

const AboutPage: React.FC = () => {
  const [activeSection, setActiveSection] = useState<string | null>(null);

  useEffect(() => {
    const handleScroll = () => {
      const sections = aboutNavLinks.map((navLink) =>
        document.getElementById(navLink.id),
      );
      const currentSection = sections.find(
        (section) =>
          section &&
          section.offsetTop <= window.scrollY &&
          section.offsetTop + section.offsetHeight > window.scrollY,
      );
      setActiveSection(currentSection ? currentSection.id : null);
    };

    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <>
      <main>
        <div className="pointer-events-none absolute left-0 -z-10 size-96 -translate-x-1/2 rounded-full bg-teal-300 opacity-40 blur-[100px]" />
        <div className="pointer-events-none absolute right-0 top-1/4 -z-10 contents size-[36rem] translate-x-1/2 rounded-full bg-teal-300 opacity-80 blur-[200px]" />

        <Title title="Every year, over 1.3 billion tons of CO₂ emissions are generated by vehicles worldwide. Nearly 70% of car seats and over 60% of bike passenger seats remain empty during daily commutes." />

        <span className="mb-4 ml-1 mt-1 block text-center text-xxs opacity-80">
          Source:&nbsp;
          <a
            href="https://www.iea.org/reports/co2-emissions-in-2022"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-teal-500"
          >
            IEA Global CO₂ Emissions 2023
          </a>
          ,&nbsp;
          <a
            href="https://openknowledge.worldbank.org/handle/10986/31433"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-teal-500"
          >
            World Bank: Motorization Management 2019
          </a>
        </span>

        <div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-0 xl:flex-row xl:gap-12">
          <div className="sticky top-0 max-h-fit w-full rounded-full bg-teal-100 p-4 dark:bg-dark xl:max-w-xs xl:rounded-none xl:pt-20">
            <ul className="flex w-full items-center justify-around xl:flex-col xl:items-start xl:gap-12">
              {aboutNavLinks.map((navLink, index) => (
                <li key={navLink.id}>
                  <a
                    href={`#${navLink.id}`}
                    className={`transition-300 flex flex-col items-start gap-1 text-sm uppercase md:items-center md:text-base xl:items-start ${
                      activeSection === navLink.id
                        ? 'font-extrabold text-teal-400 lg:text-xl xl:text-4xl'
                        : 'font-normal lg:text-base xl:text-2xl xl:opacity-30'
                    }`}
                  >
                    <span className="hidden text-sm sm:block">
                      0{index + 1}
                    </span>
                    {navLink.title}
                  </a>
                </li>
              ))}
            </ul>
          </div>
          <aside className="space-y-3 md:container xl:space-y-12">
            {aboutNavLinks.map((navLink) => (
              <section
                key={navLink.id}
                id={navLink.id}
                className="pt-10 sm:pt-0"
              >
                <img
                  src={navLink.image}
                  alt={navLink.title}
                  className="mb-6 w-full sm:mb-8 md:mb-10"
                />
                <p className="text-sm text-gray-700 dark:text-light/80 sm:text-base md:text-lg lg:text-xl">
                  {navLink.description}
                </p>
              </section>
            ))}
          </aside>
        </div>
      </main>
    </>
  );
};

export default AboutPage;
